### ISSUE TITLE
error in running diHMM

### ISSUE THREAD

**Issue by brini123** [gcyuan/diHMM#1]
Hello,

I am trying to use diHMM to do identification of Histone mark in mouse neural stem cell data. I first ran ChromHMM BinarizeBed and used the output to run diHMM with - 
 
runDiHMMTrain({'NSC'}, 'mm10', 20, 10, 'modelNSCmm10',  1)

It ran fine first time and generated two bed files for the two levels. But second time onwards I keep getting the following errors - 

Attempted to access indexTransitions(0); index must be a positive integer or
logical.

Error in saveBedFiles>saveFile (line 109)
            stateNames = [states(transitions); states(indexTransitions(end)+1)];

Error in saveBedFiles (line 17)
saveFile(filenameBinLevelStatesColor, model, cellType, 'binLevel', 'color')

Error in runDiHMMTrain (line 144)
    saveBedFiles(bedFileBaseName, modelFinal)

I debugged the code and in the saveFile function although the indexTransitions is empty the code attempts to execute the following line 

 stateNames = [states(transitions); states(indexTransitions(end)+1)];

I am not sure why the error keeps popping up and was wondering if I can get some help with the issue. I have attached the mat files. 

Thank you!
[diHMM_mat.zip](https://github.com/gcyuan/diHMM/files/843285/diHMM_mat.zip)

**Comment by eugeniomarco** [comment]
Hello,

From the error, it looks as if you only have a single state in at least one of the chromosomes and thus no transitions between states.

I'll look into the mat file you sent to see if that is the case and let you know what I find.

Thanks,

Eugenio

**Comment by brini123** [comment]
Thank you for the response.
I was wondering is it because of the way the banalized bed files were
generated? I had control data for some HM and no control for some HM. I
configured the cell-mark file accordingly.
But in the output log of Binarizebed I found a warning - Did not find
control for the two HM and treated as missing.

Thank you,
Sharmi

**Comment by eugeniomarco** [comment]
Hello Sharmi,

Could you try now after the latest commit?

As I suspected, the problem was that for some of your chromosomes you had a single state for the whole chromosome (ie, chr4, binstates), and the code expected to have at least one transition. Now it will save the bed file with a single state in the whole chromosome.

Let us know if that fixes the problem.

Thank you for using diHMM and let us know about the problem.

Regards,
Eugenio

**Comment by brini123** [comment]
Thank you very much for the update. I have downloaded the new diHMM zip
from Git

I will run it and let you know.

Best,
Sharmi

**Comment by brini123** [comment]
Hello,

The code runs fine now. Thank you very much!

Best,
Sharmi

**Comment by gcyuan** [comment]
Hi Sharmi

Thanks again for using diHMM. Please feel free to contact us to you have any trouble in in the future.

Best
GC

**Comment by eugeniomarco** [comment]
Hi Sharmi,

Glad to hear it works now! Thank you for letting us know about this issue and please let us know if you have more problems with the code.

Regards
Eugenio
