### ISSUE TITLE
bin2dec files not generated

### ISSUE THREAD

**Issue by brini123** [gcyuan/diHMM#3]
Hello, 

When using banalized files generated by chromHMM, there is a list of bin2dec text files created as well. In the diHMM package for the K562 cell line, the number of these files is equal to the binary files (one for each chromosome). I am running for mm10 and with 30 domain and 30 nucleosome levels, and I see only one bin2de file created for chr17, although there are 22 binary files for the other chromosomes. The code is running so far without any error but no other bin2dec files has been created. I wanted to know is it okay if there is just one such file or there is something wrong?

Thank you,
Sharmi

**Comment by gcyuan** [comment]
Hi
The reason is that only chr17 was used for model training. This was due to speed limitation and discussed in our Nat Comm paper.
GC

**Comment by eugeniomarco** [comment]
Hi Sharmi,

GC is right. bin2dec txt files are just a more compact version of the
binarized files. When the model is trained on chr17 they are created for
that chromosome.

Thanks,
Eugenio

**Comment by eugeniomarco** [comment]
Hi Sharmi,

One more thing. Has your code finished the training? I think at the final step, when you decode and assign states for the whole genome, the binarized files for all the chromosomes will be read and the bin2dec files for all of them will be created.

Eugenio

**Comment by brini123** [comment]
Thank you for the response.

The code is still running. I will wait for it to finish and then check the
bin2dec folder again.
I had guessed that the training is done only for Chr17 but was not sure
since when I use 20-10 nucleosome-domain combination the files for all the
chromosomes are created after a few minutes of starting the code.

 I am guessing for 30-30 nucleosome-domain combination the time complexity
increases resulting in the algorithm to train only on chromosome 17?

Thank you,
Sharmi
