### ISSUE TITLE
error in bin2dec function 

### ISSUE THREAD

**Issue by brini123** [gcyuan/diHMM#5]
Hello,

I am interested in analyzing enrichment of transcription factors instead of just histone marks in the genome and to that end, I am  using diHMM to do the genome segmentation. 

I used ChrommHMM first to binarize the bed files (I used -peaks option since I have the pre-processed peak files and not the bam files. I believe this option is not recommended for broad peak calls, but since in this case it is TFs, I believe it should be okay).

When I run diHMM on the banarized file on chrmosome 17 (default), I get an error in the bin2dec function

`Binary string must be 52 bits or less.`

I checked in the code that the input to bin2dec function is the binary matrix obtained by num2str(cell2mat(data)), and if the number of columns of the binary matrix is more than 52 there will be an error. In my matrix, the size is [474936,  67], hence the error. 

I was wondering if I made a mistake? Or is there a way to bypass the error? Or diHMM can only be used to cluster genome segments when used with the bam files and without -peaks option. 

I have used diHMM before (without the -peaks option), but did not encounter this problem.

I would really appreciate some help.

Thank you,
Sharmi

**Comment by gcyuan** [comment]
Hi Sharmi
We have not tested diHMM on TF binding data yet, although in principle this should be doable. I suggest you to compare the input bed file with one generated from histone modification data which you successfully processed by diHMM before. Hope this is helpful.
Best
GC

**Comment by brini123** [comment]
Thank you very much for the reply Dr. Yuan. I     will do a comparison.

Thank you,
Sharmi

**Comment by gcyuan** [comment]
Great. If it is fine with you I will close the issue.

**Comment by brini123** [comment]
Sure.

Thank you,
Sharmi
